apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketmaster-mongo
  template:
    metadata:
      labels:
        app: ticketmaster-mongo
    spec:
      containers: 
        - name : ticketmaster-mongo
          image: mongo

--- 

apiVersion: v1
kind: Service
metadata:
  name: ticketmaster-mongo-srv
spec:
  selector:
    app: ticketmaster-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017 